# Limpieza y procesado de datos

In [1]:
!pip install missingno

Requirement already satisfied: missingno in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (0.5.2)
Requirement already satisfied: scipy in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from missingno) (1.15.2)
Requirement already satisfied: numpy in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from missingno) (2.2.3)
Requirement already satisfied: matplotlib in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from missingno) (3.10.0)
Requirement already satisfied: seaborn in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from missingno) (0.13.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (3.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: packaging>=20.0 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (24.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from seaborn->missingno) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\nuria\onedrive\escritorio\ml_student_depression\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Librer√≠as

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from missingno import matrix
import missingno as msno

In [2]:
df = pd.read_csv(r'C:\Users\nuria\OneDrive\Escritorio\ML_student_depression\data\raw\Student Depression Dataset.csv')
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

### Opciones
- Eliminar la columnas 'City', 'Profession', 'Work Pressure', 'Job Satisfaction', 'Degree'
- Numerar las columnas 'Sleep Duration' y 'Dietary habits'
- Convertir los yes y no en 0 y 1

In [3]:
eliminar = ['id', 'City', 'Profession', 'Work Pressure', 'Job Satisfaction', 'Degree']
df = df.drop(columns=eliminar) 
df.head()

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,33.0,5.0,8.97,2.0,5-6 hours,Healthy,Yes,3.0,1.0,No,1
1,Female,24.0,2.0,5.90,5.0,5-6 hours,Moderate,No,3.0,2.0,Yes,0
2,Male,31.0,3.0,7.03,5.0,Less than 5 hours,Healthy,No,9.0,1.0,Yes,0
3,Female,28.0,3.0,5.59,2.0,7-8 hours,Moderate,Yes,4.0,5.0,Yes,1
4,Female,25.0,4.0,8.13,3.0,5-6 hours,Moderate,Yes,1.0,1.0,No,0

In [16]:
df.tail(8)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27893,Female,24.0,3.0,6.02,2.0,7-8 hours,Moderate,No,8.0,2.0,No,0
27894,Male,23.0,3.0,6.00,2.0,More than 8 hours,Healthy,Yes,12.0,4.0,No,0
27895,Male,31.0,2.0,7.27,5.0,7-8 hours,Moderate,Yes,6.0,1.0,Yes,0
27896,Female,27.0,5.0,5.75,5.0,5-6 hours,Unhealthy,Yes,7.0,1.0,Yes,0
27897,Male,27.0,2.0,9.40,3.0,Less than 5 hours,Healthy,No,0.0,3.0,Yes,0
27898,Male,31.0,3.0,6.61,4.0,5-6 hours,Unhealthy,No,12.0,2.0,No,0
27899,Female,18.0,5.0,6.88,2.0,Less than 5 hours,Healthy,Yes,10.0,5.0,No,1
27900,Male,27.0,4.0,9.24,1.0,Less than 5 hours,Healthy,Yes,2.0,3.0,Yes,1

### Transformaciones:
- Gender: Male: 1, Female: 0
- Sleep Duration: 5-6 hours: 0, 7-8 hours: 1, Less than 5 hours: 2, More than 8 hours: 3
- Dietary Habits: Healthy: 0, Moderate: 1, Unhealthy: 3 ¬ø?

#### Conclusi√≥n: 
El LabaelEncoder no atribuye los numeros adecuados, hay que hacerlo manualmente

In [5]:
df.head()

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,33.0,5.0,8.97,2.0,5-6 hours,Healthy,Yes,3.0,1.0,No,1
1,Female,24.0,2.0,5.90,5.0,5-6 hours,Moderate,No,3.0,2.0,Yes,0
2,Male,31.0,3.0,7.03,5.0,Less than 5 hours,Healthy,No,9.0,1.0,Yes,0
3,Female,28.0,3.0,5.59,2.0,7-8 hours,Moderate,Yes,4.0,5.0,Yes,1
4,Female,25.0,4.0,8.13,3.0,5-6 hours,Moderate,Yes,1.0,1.0,No,0

In [4]:
gender = {'Male': 1, 'Female':0}
df['Gender'] = df['Gender'].map(gender)
df['Gender'] = df['Gender'].astype(int)
df.head(3)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,5-6 hours,Healthy,Yes,3.0,1.0,No,1
1,0,24.0,2.0,5.90,5.0,5-6 hours,Moderate,No,3.0,2.0,Yes,0
2,1,31.0,3.0,7.03,5.0,Less than 5 hours,Healthy,No,9.0,1.0,Yes,0

In [5]:
sleep = {'More than 8 hours': 0, '7-8 hours': 1, '5-6 hours': 2, 'Less than 5 hours': 3, 'Others':4}
df['Sleep Duration'] = df['Sleep Duration'].map(sleep)
df['Sleep Duration'] = df['Sleep Duration'].astype(int)
df.head(3)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,2,Healthy,Yes,3.0,1.0,No,1
1,0,24.0,2.0,5.90,5.0,2,Moderate,No,3.0,2.0,Yes,0
2,1,31.0,3.0,7.03,5.0,3,Healthy,No,9.0,1.0,Yes,0

In [6]:
diet = {'Healthy': 0, 'Moderate': 1, 'Unhealthy': 2, 'Others': 3}
df['Dietary Habits'] = df['Dietary Habits'].map(diet)
df['Dietary Habits'] = df['Dietary Habits'].astype(int)
df.head(3)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,2,0,Yes,3.0,1.0,No,1
1,0,24.0,2.0,5.90,5.0,2,1,No,3.0,2.0,Yes,0
2,1,31.0,3.0,7.03,5.0,3,0,No,9.0,1.0,Yes,0

In [7]:
suicidals = {'No': 0, 'Yes': 1}
df['Have you ever had suicidal thoughts ?'] = df['Have you ever had suicidal thoughts ?'].map(suicidals)
df['Have you ever had suicidal thoughts ?'] = df['Have you ever had suicidal thoughts ?'].astype(int)
df.head(3)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,2,0,1,3.0,1.0,No,1
1,0,24.0,2.0,5.90,5.0,2,1,0,3.0,2.0,Yes,0
2,1,31.0,3.0,7.03,5.0,3,0,0,9.0,1.0,Yes,0

In [8]:
mentals = {'No': 0, 'Yes': 1}
df['Family History of Mental Illness'] = df['Family History of Mental Illness'].map(mentals)
df['Family History of Mental Illness'] = df['Family History of Mental Illness'].astype(int)
df.head(3)

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,2,0,1,3.0,1.0,0,1
1,0,24.0,2.0,5.90,5.0,2,1,0,3.0,2.0,1,0
2,1,31.0,3.0,7.03,5.0,3,0,0,9.0,1.0,1,0

In [15]:
print(df['Dietary Habits'].unique())

['Healthy' 'Moderate' 'Unhealthy' 'Others']

### Cambios realizados:
- Gender = 'Male': 1, 'Female':0
- Sleep Duration = 'More than 8 hours': 0, '7-8 hours': 1, '5-6 hours': 2, 'Less than 5 hours': 3, 'Others':4
- Dietary Habits = 'Healthy': 0, 'Moderate': 1, 'Unhealthy': 2, 'Others': 3
- Have you ever had suicidal thoughts ? = 'No': 0, 'Yes': 1
- Family History of Mental Illness = 'No': 0, 'Yes': 1

In [22]:
print(df.shape)
print('-----------------------------------------------------------------------------------')
print(df.columns)
print('-----------------------------------------------------------------------------------')
print(df.info())
print('-----------------------------------------------------------------------------------')

(27901, 12)
-----------------------------------------------------------------------------------
Index(['Gender', 'Age', 'Academic Pressure', 'CGPA', 'Study Satisfaction',
       'Sleep Duration', 'Dietary Habits',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')
-----------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 12 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27901 non-null  int64
 1   Age                                    27901 non-null  float64
 2   Academic Pressure                      27901 non-null  float64
 3   CGPA                                   27901 non-null  float64
 4   Study Satisfaction                     27901 non-null  float64
 5   Sleep Duration                         27901 non-null  int64
 6   Dietary Habits                         27901 non-null  int64
 7   Have you ever had suicidal thoughts ?  27901 non-null  int64
 8   Work/Study Hours                       27901 non-null  float64
 9   Financial Stress                       27898 non-null  float64
 10  Family History of Mental Illness       27901 non-null  int64
 11  Depression                             27901 non-null  int64
dtypes: float64(6), int64(6)
memory usage: 2.6 MB
None
-----------------------------------------------------------------------------------

In [23]:
print(df.isnull().sum())

Gender                                   0
Age                                      0
Academic Pressure                        0
CGPA                                     0
Study Satisfaction                       0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

Dado que solamente existen 3 valores nulos y est√°n unicamnete en la columna 'Financial Stress' se opta por eliminarlos ya que no se les considera representativos en comparaci√≥n con el tama√±o total del conjunto de datos y no va a afectar mucho en los resultados

In [27]:
# Eliminaci√≥n de los Nan de la columna Financial Stress
df = df.dropna(subset=['Financial Stress'])
df.head()

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,5.0,8.97,2.0,2,0,1,3.0,1.0,0,1
1,0,24.0,2.0,5.90,5.0,2,1,0,3.0,2.0,1,0
2,1,31.0,3.0,7.03,5.0,3,0,0,9.0,1.0,1,0
3,0,28.0,3.0,5.59,2.0,1,1,1,4.0,5.0,1,1
4,0,25.0,4.0,8.13,3.0,2,1,1,1.0,1.0,0,0

In [28]:
print(df.isnull().sum())

Gender                                   0
Age                                      0
Academic Pressure                        0
CGPA                                     0
Study Satisfaction                       0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [29]:
# Guarda el DataFrame modificado en un nuevo archivo CSV
df.to_csv("dataset_limpio.csv", index=False)